<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>CimBios.Utils.MetaReflectionHelper</Title>
        <Authors>CimBios Org</Authors>
        <Description>Core data model library. Reflection helpers to core library serializable entities.</Description>
        <Copyright>Copyright (C) 2025 Yuri A. Kovalenko a.k.a belizahrt &lt;belizahrt@gmail.com&gt;</Copyright>
        <PackageProjectUrl>https://github.com/Cimbios/CimBios.Core</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Cimbios/CimBios.Core</RepositoryUrl>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
    </PropertyGroup>
</Project>